name: Food Delivery — Local
values:
  - key: baseUrl
    value: 'http://localhost:3000/api'
  - key: serverOrigin
    value: 'http://localhost:3000'
  - key: accessToken
    value: ''
  - key: refreshToken
    value: ''
  - key: ownerAccessToken
    value: ''
  - key: driverAccessToken
    value: ''
  - key: restaurantId
    value: ''
  - key: categoryId
    value: ''
  - key: menuItemId
    value: ''
  - key: orderId
    value: ''
  - key: passwordResetToken
    value: ''
  - key: search
    value: ''
  - key: cuisineType
    value: ''
